2024-10-08 14:13:44,652 INFO    StreamThr :19256 [internal.py:wandb_internal():85] W&B internal server running at pid: 19256, started at: 2024-10-08 14:13:44.650657
2024-10-08 14:13:44,661 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status
2024-10-08 14:13:44,665 INFO    WriterThread:19256 [datastore.py:open_for_write():87] open: .\wandb\run-20241008_141344-ox4xjejb\run-ox4xjejb.wandb
2024-10-08 14:13:44,671 DEBUG   SenderThread:19256 [sender.py:send():379] send: header
2024-10-08 14:13:44,672 DEBUG   SenderThread:19256 [sender.py:send():379] send: run
2024-10-08 14:13:44,678 INFO    SenderThread:19256 [sender.py:_setup_resume():749] checking resume status for None/rl4co/ox4xjejb
2024-10-08 14:13:46,342 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: check_version
2024-10-08 14:13:46,393 INFO    SenderThread:19256 [dir_watcher.py:__init__():211] watching files in: .\wandb\run-20241008_141344-ox4xjejb\files
2024-10-08 14:13:46,394 INFO    SenderThread:19256 [sender.py:_start_run_threads():1188] run started: ox4xjejb with start time 1728368024.652656
2024-10-08 14:13:46,394 DEBUG   SenderThread:19256 [sender.py:send_request():406] send_request: check_version
2024-10-08 14:13:47,885 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: run_start
2024-10-08 14:13:48,146 DEBUG   HandlerThread:19256 [system_info.py:__init__():26] System info init
2024-10-08 14:13:48,146 DEBUG   HandlerThread:19256 [system_info.py:__init__():41] System info init done
2024-10-08 14:13:48,146 INFO    HandlerThread:19256 [system_monitor.py:start():194] Starting system monitor
2024-10-08 14:13:48,147 INFO    HandlerThread:19256 [system_monitor.py:probe():214] Collecting system info
2024-10-08 14:13:48,149 INFO    SystemMonitor:19256 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-08 14:13:48,150 INFO    SystemMonitor:19256 [interfaces.py:start():188] Started cpu monitoring
2024-10-08 14:13:48,157 INFO    SystemMonitor:19256 [interfaces.py:start():188] Started disk monitoring
2024-10-08 14:13:48,160 INFO    SystemMonitor:19256 [interfaces.py:start():188] Started gpu monitoring
2024-10-08 14:13:48,162 INFO    SystemMonitor:19256 [interfaces.py:start():188] Started memory monitoring
2024-10-08 14:13:48,163 DEBUG   HandlerThread:19256 [system_info.py:probe():152] Probing system
2024-10-08 14:13:48,164 DEBUG   HandlerThread:19256 [system_info.py:probe():200] Probing system done
2024-10-08 14:13:48,164 DEBUG   HandlerThread:19256 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.15', 'heartbeatAt': '2024-10-08T06:13:48.164535', 'startedAt': '2024-10-08T06:13:44.476424', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'E:\\rl4ev\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'DESKTOP-4UKOA1U', 'username': '78788', 'executable': 'd:\\py\\Anaconda3\\envs\\pytorch\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 6, 'cpu_freq': {'current': 2901.0, 'min': 0.0, 'max': 2901.0}, 'cpu_freq_per_core': [{'current': 2901.0, 'min': 0.0, 'max': 2901.0}], 'disk': {'/': {'total': 953.8369140625, 'used': 35.0166015625}}, 'gpu': 'NVIDIA GeForce GTX 1050 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1050 Ti', 'memory_total': 4294967296}], 'memory': {'total': 7.857707977294922}}
2024-10-08 14:13:48,164 INFO    HandlerThread:19256 [system_monitor.py:probe():224] Finished collecting system info
2024-10-08 14:13:48,164 INFO    HandlerThread:19256 [system_monitor.py:probe():227] Publishing system info
2024-10-08 14:13:48,165 DEBUG   HandlerThread:19256 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-08 14:13:48,166 INFO    SystemMonitor:19256 [interfaces.py:start():188] Started network monitoring
2024-10-08 14:13:48,190 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:48,190 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:48,405 INFO    Thread-17 :19256 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20241008_141344-ox4xjejb\files\conda-environment.yaml
2024-10-08 14:13:50,217 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:50,218 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:52,505 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:52,506 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:54,878 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:54,879 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:57,168 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:57,168 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:59,457 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:13:59,458 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:01,752 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:01,753 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:03,204 ERROR   HandlerThread:19256 [system_info.py:_save_conda():223] Error saving conda packages: Command '['conda', 'env', 'export']' timed out after 15 seconds
Traceback (most recent call last):
  File "d:\py\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 216, in _save_conda
    subprocess.call(
  File "d:\py\Anaconda3\envs\pytorch\lib\subprocess.py", line 351, in call
    return p.wait(timeout=timeout)
  File "d:\py\Anaconda3\envs\pytorch\lib\subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "d:\py\Anaconda3\envs\pytorch\lib\subprocess.py", line 1473, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['conda', 'env', 'export']' timed out after 15 seconds
2024-10-08 14:14:03,209 DEBUG   HandlerThread:19256 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-08 14:14:03,214 INFO    HandlerThread:19256 [system_monitor.py:probe():229] Finished publishing system info
2024-10-08 14:14:03,227 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:03,227 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: keepalive
2024-10-08 14:14:03,227 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:03,227 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: keepalive
2024-10-08 14:14:03,228 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:03,228 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: keepalive
2024-10-08 14:14:03,229 DEBUG   SenderThread:19256 [sender.py:send():379] send: files
2024-10-08 14:14:03,230 INFO    SenderThread:19256 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-08 14:14:03,519 INFO    Thread-17 :19256 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20241008_141344-ox4xjejb\files\wandb-metadata.json
2024-10-08 14:14:04,045 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:04,046 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:04,253 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: python_packages
2024-10-08 14:14:04,254 DEBUG   SenderThread:19256 [sender.py:send_request():406] send_request: python_packages
2024-10-08 14:14:04,258 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: stop_status
2024-10-08 14:14:04,259 DEBUG   SenderThread:19256 [sender.py:send_request():406] send_request: stop_status
2024-10-08 14:14:04,269 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-08 14:14:04,531 INFO    Thread-17 :19256 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20241008_141344-ox4xjejb\files\requirements.txt
2024-10-08 14:14:04,589 DEBUG   SenderThread:19256 [sender.py:send():379] send: telemetry
2024-10-08 14:14:04,589 DEBUG   SenderThread:19256 [sender.py:send():379] send: telemetry
2024-10-08 14:14:04,590 DEBUG   SenderThread:19256 [sender.py:send():379] send: metric
2024-10-08 14:14:04,590 DEBUG   SenderThread:19256 [sender.py:send():379] send: telemetry
2024-10-08 14:14:04,590 DEBUG   SenderThread:19256 [sender.py:send():379] send: metric
2024-10-08 14:14:04,591 WARNING SenderThread:19256 [sender.py:send_metric():1405] Seen metric with glob (shouldn't happen)
2024-10-08 14:14:04,856 INFO    wandb-upload_0:19256 [upload_job.py:push():130] Uploaded file C:\Users\78788\AppData\Local\Temp\tmpevh6nf5gwandb\q5h1270s-wandb-metadata.json
2024-10-08 14:14:05,600 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:06,367 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:06,368 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:08,659 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:08,659 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:10,646 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:10,946 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:10,947 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:11,597 INFO    Thread-17 :19256 [dir_watcher.py:_on_file_modified():288] file/dir modified: .\wandb\run-20241008_141344-ox4xjejb\files\conda-environment.yaml
2024-10-08 14:14:13,250 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:13,251 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:15,552 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:15,552 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:15,687 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:16,635 INFO    Thread-17 :19256 [dir_watcher.py:_on_file_modified():288] file/dir modified: .\wandb\run-20241008_141344-ox4xjejb\files\config.yaml
2024-10-08 14:14:17,846 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:17,846 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:20,150 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:20,151 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:21,040 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:22,497 ERROR   gpu       :19256 [interfaces.py:aggregate():159] Failed to serialize metric: division by zero
2024-10-08 14:14:22,507 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:22,509 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:24,764 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:24,764 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:26,069 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:27,070 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:27,070 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:29,358 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:29,358 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:31,087 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:31,650 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:31,650 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:33,941 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:33,942 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:36,126 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: status_report
2024-10-08 14:14:36,230 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:36,230 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:37,879 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-08 14:14:37,880 DEBUG   HandlerThread:19256 [handler.py:handle_request():158] handle_request: stop_status
2024-10-08 14:14:37,881 DEBUG   SenderThread:19256 [sender.py:send_request():406] send_request: stop_status
2024-10-08 14:14:38,242 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-10-08 14:14:38,242 ERROR   gpu       :19256 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
