val_file not set. Generating dataset instead
test_file not set. Generating dataset instead
Backend tkagg is interactive backend. Turning interactive mode on.
C:\research_code\rl4co-main\rl4co\models\nn\attention.py:128: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  out = self.sdpa_fn(
c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py:55: MatplotlibDeprecationWarning: The interactive_bk attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin(matplotlib.backends.BackendFilter.INTERACTIVE)`` instead.
  from matplotlib.rcsetup import interactive_bk, non_interactive_bk  # @UnresolvedImport
c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py:55: MatplotlibDeprecationWarning: The non_interactive_bk attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin(matplotlib.backends.BackendFilter.NON_INTERACTIVE)`` instead.
  from matplotlib.rcsetup import interactive_bk, non_interactive_bk  # @UnresolvedImport
Traceback (most recent call last):
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Administrator\.cursor\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\rl4ev\train.py", line 66, in <module>
    main()
  File "D:\rl4ev\train.py", line 54, in main
    trainer.fit(model)
  File "C:\research_code\rl4co-main\rl4co\utils\trainer.py", line 146, in fit
    super().fit(
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 948, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\call.py", line 96, in _call_setup_hook
    _call_lightning_module_hook(trainer, "setup", stage=fn)
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\lightning\pytorch\trainer\call.py", line 159, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\research_code\rl4co-main\rl4co\models\rl\common\base.py", line 155, in setup
    self.post_setup_hook()
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\reinforce.py", line 119, in post_setup_hook
    self.baseline.setup(
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 117, in setup
    self.baseline.setup(*args, **kw)
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 174, in setup
    self._update_policy(*args, **kw)
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 187, in _update_policy
    self.rollout(self.policy, env, batch_size, device, self.dataset).cpu().numpy()
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 242, in rollout
    rewards = torch.cat([eval_policy(batch) for batch in dl], 0)
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 242, in <listcomp>
    rewards = torch.cat([eval_policy(batch) for batch in dl], 0)
  File "C:\research_code\rl4co-main\rl4co\models\rl\reinforce\baselines.py", line 238, in eval_policy
    return policy(batch, env, decode_type="greedy")["reward"]
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\Administrator\anaconda3\envs\RL4CO\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\research_code\rl4co-main\rl4co\models\common\constructive\base.py", line 237, in forward
    td = env.step(td)["next"]
  File "C:\research_code\rl4co-main\rl4co\envs\common\base.py", line 129, in step
    td = self._step(td)
  File "D:\rl4ev\evrp\env.py", line 164, in _step
    + chg_mat[active_indices, prior_node[active_indices], current_node[active_indices]].float()
RuntimeError: The size of tensor a (91) must match the size of tensor b (100) at non-singleton dimension 0